[package]
name = "dedupe"
version = "0.1.1"
authors = ["David Raifaizen <d-raif@hotmail.com>"]

[dependencies]
csv = "0.15.0"
fst = "0.3"
fst-levenshtein = "0.2"
lazy_static = "1.0.0"
regex = "0.2.10"
